name: Node.js CI
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cat .aws/credentials.template | sed "s@%AWS_ACCESS_KEY_ID%@$AWS_ACCESS_KEY_ID@g;s@%AWS_SECRET_ACCESS_KEY%@$AWS_SECRET_ACCESS_KEY@g" > .aws/credentials
          mkdir ~/.aws && cp -r .aws/credentials ~/.aws
      - name: Install npm packages
        run: |
          npm run prepare
          npm install
          nohup npm run dev > output.log 2>&1 &
          sleep 5
          curl -I http://localhost:5173/
      - name: Run Cypress tests
        run: |
          npm run test:cypress
      - name: Run Playwright tests
        run: |
          npx playwright install chromium
          npm run test:playwright
