name: Node.js CI
on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Install npm packages
        run: |
          npm install
          nohup npm run dev > output.log 2>&1 &
          sleep 5
          curl -I http://localhost:1342/

      - name: Run Cypress tests
        run: |
          npm run test:cypress

      - name: Run Playwright tests
        run: |
          npx playwright install chromium
          npm run test:playwright

      - name: Run Puppeteer tests
        run: |
          npm run test:puppeteer

      - name: Prepare java tests
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: JUnit 5 tests
        run: cd ${GITHUB_WORKSPACE}/selenium-java && ./mvnw test --batch-mode --file pom.xml
