name: Node.js CI
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Install npm packages
        run: |
          npm rum prepare
          npm install
          nohup npm run dev > output.log 2>&1 &
          sleep 5
          curl -I http://localhost:5173/
      - name: Run Cypress run
        run: |
          npm run test:cypress

          
