name: Node.js CI
on:
  pull_request:
    branches: ["test1"]
  push:
    branches: ["test1"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Install npm packages
        run: |
          npm install
          nohup npm run dev > output.log 2>&1 &
          sleep 5
          curl -I http://localhost:1342/

      - name: Run Playwright tests
        run: |
          npx playwright install chromium
          npm run test:playwright
      - name: UserWay Accessibility Analysis
        uses: UserWayOrg/cicd-action@main #`main` or `qa`, depending on what env you need
        with:
          token: ${{ secrets.USERWAY_TOKEN }}
          report_paths: "./uw-a11y-reports"
